name: 'Sha Java CI'
description: 'A collection of common java jobs and cache operations'
inputs:
  java-version:
    description: 'The Java version to set up. Takes a whole or semver Java version.'
    required: true
    default: 17
  java-distribution:
    description: 'Java distribution.'
    required: true
    default: 'adopt'
  codacy-project-token:
    description: 'Codacy Project token taken from codacy'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}
        cache: gradle
    - name: Run tests
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ inputs.codacy-project-token }}
        coverage-reports: build/reports/jacoco/test/jacocoTestReport.xml
    - run: goodbye.sh
      shell: bash
